[package]
name = "study3"
version = "0.1.0"
edition = "2021"
# ABC
# CASE_INSENSITIVE=1 cargo run c Cargo.toml
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
